run-name: "CI/CD pipeline"
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: sudo apt-get install g++ make cmake -y

      - name: Creating directory for building
        run: mkdir build && cd build && cmake .. && make -j`nproc` && cd ../

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

  Autotests:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Run gtest
        run: sudo chmod +x ./run_tests && ./run_tests



  Linters-check:
    runs-on: ubuntu-latest
    needs: Autotests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cppcheck
        run: sudo apt-get install cppcheck -y

      - name: Run cppcheck on the source code
        run: |
          cppcheck --enable=all --inconclusive --error-exitcode=1 \
          --suppress=syntaxError \
          --suppress=unusedVariable \
          --suppress=strPlusChar \
          --suppress=initializerList \
          --suppress=noExplicitConstructor \
          --suppress=unusedFunction \
          --suppress=unreadVariable \
          --suppress=missingInclude \
          --suppress=unassignedVariable \
          --suppress=constParameter \
          --suppress=useStlAlgorithm \
          --suppress=uninitMemberVar \
          --force \
          ./
  

  Docs-generating:
    runs-on: ubuntu-latest
    needs: Linters-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs

