name: GitHub Actions Demo
run-name: "CI/CD pipeline"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing dependencies
        run: sudo apt-get install g++ make cmake -y
      - name: Creating directory for building
        run: mkdir build && cd build && cmake .. && make -j`nproc`


  Autotests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run gtest
        run: sudo chmod +x ./run_tests && ./run_tests

  Check linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install cppcheck
        run: sudo apt-get install cppcheck -y
      - name: Run cppcheck on the source code
        run: cppcheck --enable=all --inconclusive --error-exitcode=1 ../
